### ISSUE TITLE
using dsfr-connect with Vuetify is not working 

### ISSUE THREAD

**Issue by nabanoub** [sneko/dsfr-connect#3]
## Current Behavior

- First issue is :- 
```
 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/dsfr-connect/src/common/index.ts:1:26: ERROR: Could not resolve "@codegouvfr/react-dsfr"
```
 * as a work-around I have installed ` "@codegouvfr/react-dsfr": "^0.60.0"` as a dev dependency.
 
 - Second issue is , 
 
```
 Can't find stylesheet to import.
    ╷
  1 │ @use '@gouvfr/dsfr/module/spacing' as dsfrSpacing;
```

 * as a work-around I have installed ` "@gouvfr/dsfr": "^1.9.3"` as a dev dependency.

- Third issue  :-

```
Vuetify({
      autoImport: true,
      styles: { configFile: 'node_modules/dsfr-connect/src/vuetify-v3/settings.scss' },
    }),
```
```

8:42:19 AM [vite] Pre-transform error: [sass] Can't find stylesheet to import.
  ╷
4 │ @use 'module/string';
  │ ^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@gouvfr\dsfr\module\spacing\function\_space.scss 4:1  @forward
  node_modules\@gouvfr\dsfr\module\spacing\_index.scss 2:1           @use
  node_modules\dsfr-connect\src\vuetify-v3\settings.scss 1:1         @use
  plugin-vuetify:components\VApp\VApp.sass 1:1                      root stylesheet
8:42:19 AM [vite] Pre-transform error: [sass] Can't find stylesheet to import.
  ╷
4 │ @use 'module/string';
  │ ^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@gouvfr\dsfr\module\spacing\function\_space.scss 4:1  @forward
  node_modules\@gouvfr\dsfr\module\spacing\_index.scss 2:1           @use
  node_modules\dsfr-connect\src\vuetify-v3\settings.scss 1:1         @use
  plugin-vuetify:components\VMain\VMain.sass 1:1                    root stylesheet
8:42:19 AM [vite] Pre-transform error: [sass] Can't find stylesheet to import.
  ╷
4 │ @use 'module/string';
  │ ^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@gouvfr\dsfr\module\spacing\function\_space.scss 4:1  @forward
  node_modules\@gouvfr\dsfr\module\spacing\_index.scss 2:1           @use
  node_modules\dsfr-connect\src\vuetify-v3\settings.scss 1:1         @use
  plugin-vuetify:styles\main.sass 1:1                               root stylesheet
```

## Environment

- Version: 1.1.0
- Platform:  Windows 10
- Node.js Version: v18.17.1

**Comment by sneko** [comment]
Hi @nabanoub ,

The first issue is related to an error in the documentation (it was pointing to an uncompiled JS file, so expecting some dependencies)

The second issue is due to SCSS, it uses variables from the DSFR dependency and I have no way to partially precompile the SCSS to get a SCSS without dependency bindings. It should have been better explained in the documentation to add required dependency.

I’m sorry you experienced those issues while trying to start with `dsfr-connect`. I rewrote the documentation (https://dsfr-connect.rame.fr/main/?path=/docs/dsfr-connect-utilisation-vuetify-v3--docs) and published a new version (https://github.com/sneko/dsfr-connect/releases/tag/v1.1.2). Could you give it a try and confirm I can close the issue?

Thank you,

**Comment by nabanoub** [comment]
@sneko 

it works now , thank you.
